LTS/LTS/Models/RegisterViewModel.cs
using EntityLayer.Concrete;
using System.ComponentModel.DataAnnotations;

namespace LTS.Models
{
    public class RegisterViewModel
    {
        [Display(Name = "Adınız")]
        [Required(ErrorMessage = "Lütfen Adınızı Giriniz")]
        public string Name { get; set; }

        [Display(Name = "Soyadınız")]
        [Required(ErrorMessage = "Lütfen Soyadınızı Giriniz")]
        public string SurName { get; set; }

        [Display(Name = "Telefon Numaranız")]
        [Required(ErrorMessage = "Lütfen Telefon Numarası Giriniz")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Telefon Numarası Tekrarı")]
        [Compare("PhoneNumber", ErrorMessage = "Telefon Numarası Aynı Değil")]
        public string PhoneNumberConfirm { get; set; }

        [Display(Name = "Şifreniz")]
        [Required(ErrorMessage = "Lütfen Şifrenizi Giriniz")]
        public string Password { get; set; }

        [Display(Name = "Şifre Tekrarı")]
        [Compare("Password", ErrorMessage = "Şifreler Aynı Değil")]
        public string ConfirmPassword { get; set; }

        [Display(Name = "Emailiniz")]
        [Required(ErrorMessage = "Lütfen Email Adresinizi Giriniz")]
        public string Email { get; set; }

        [Display(Name = "Kullanıcı Adınız")]
        [Required(ErrorMessage = "Lütfen Kullanıcı Adınızı Giriniz")]
        public string UserName { get; set; }
    }
}

LTS/LTS/Controllers/RegisterController.cs
using BusinessLayer.ValidationRules;
using EntityLayer.Concrete;
using FluentValidation.Results;
using LTS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace LTS.Controllers
{
    [AllowAnonymous]
    public class RegisterController : Controller
    {
        private UserManager<AppUser> _userManager;

        public RegisterController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(RegisterViewModel registerViewModel)
        {
            if (ModelState.IsValid)
            {
                if (registerViewModel.Password == registerViewModel.ConfirmPassword && registerViewModel.PhoneNumber==registerViewModel.PhoneNumberConfirm)
                {
                    AppUser user = new AppUser()
                    {
                        UserName = registerViewModel.UserName,
                        Email = registerViewModel.Email,
                        Name = registerViewModel.Name,
                        SurName = registerViewModel.SurName,
                        PhoneNumber = registerViewModel.PhoneNumber,
                    };
                    UserValidator validator = new UserValidator();
                    ValidationResult validationResult=validator.Validate(user);
                    if (validationResult.IsValid)
                    {
                        var result = await _userManager.CreateAsync(user, registerViewModel.Password);
                        if (result.Succeeded)
                        {
                            return RedirectToAction("Index", "Login");
                        }
                        else
                        {
                            foreach (var item in result.Errors)
                            {
                                ModelState.AddModelError("", item.Description);
                            }
                        }
                    }
                    else
                    {
                        foreach (var item in validationResult.Errors)
                        {
                            ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                        }
                    }
                    
                }
            }
            return View(registerViewModel);
        }
    }
}

LTS/LTS/Views/Register/Index.cshtml
@model RegisterViewModel

@{
    Layout = null;
}



<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8" />
    <title>Kayıt  Ekranı</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Responsive bootstrap 4 admin template" name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="~/assets/images/favicon.ico">

    <!-- App css -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" id="bootstrap-stylesheet" />
    <link href="~/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/app.min.css" rel="stylesheet" type="text/css" id="app-stylesheet" />

</head>

<body>

    <div class="account-pages mt-5 mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-5">
                    <div class="card">

                        <div class="text-center account-logo-box">
                            <div class="mt-2 mb-2">
                                <a href="index.html" class="text-success">
                                    <span><img src="~/assets/images/logo.png" alt="" height="36"></span>
                                </a>
                            </div>
                        </div>

                        <div class="card-body">

                            <form method="post" asp-controller="Register" asp-action="Index" role="form">
                                <div class="form-group">
                                    <span asp-validation-for="@Model.Email" class="text-danger"></span>
                                    <input class="form-control" asp-for="@Model.Email" type="email" id="Email" placeholder="Email Adresiniz">
                                </div>

                                <div class="form-group">
                                    <span asp-validation-for="@Model.Name" class="text-danger"></span>

                                    <input class="form-control" asp-for="@Model.Name" type="text" id="Name" placeholder="Adınız">
                                </div>
                                <div class="form-group">
                                    <span asp-validation-for="@Model.SurName" class="text-danger"></span>

                                    <input class="form-control" asp-for="@Model.SurName" type="text" id="SurName" placeholder="Soyadınız">
                                </div>
                                <div class="form-group">
                                    <span asp-validation-for="@Model.PhoneNumber" class="text-danger"></span>

                                    <input class="form-control" asp-for="@Model.PhoneNumber" type="text" id="PhoneNumber" placeholder="Telefon Numaranız">
                                </div>
                                <div class="form-group">
                                    <span asp-validation-for="@Model.PhoneNumberConfirm" class="text-danger"></span>

                                    <input class="form-control" asp-for="@Model.PhoneNumberConfirm" type="password" id="PhoneNumberConfirm" placeholder=" Telefon Numarası Tekrarı">
                                </div>
                                <div class="form-group">
                                    <span asp-validation-for="@Model.UserName" class="text-danger"></span>

                                    <input class="form-control" asp-for="@Model.UserName" type="text" id="UserName" placeholder="Kullanıcı Adınız">
                                </div>
                                <div class="form-group">
                                    <span asp-validation-for="@Model.Password" class="text-danger"></span>

                                    <input class="form-control" asp-for="@Model.Password" type="password" id="Password" placeholder="Şifreniz">
                                </div>

                                <div class="form-group">
                                    <span asp-validation-for="@Model.ConfirmPassword" class="text-danger"></span>

                                    <input class="form-control" asp-for="@Model.ConfirmPassword" type="password" id="ConfirmPassword" placeholder=" Şifre Tekrarı">
                                </div>

                                <div class="form-group account-btn text-center mt-2">
                                    <div class="col-12">
                                        <button class="btn width-md btn-bordered btn-danger waves-effect waves-light" type="submit">Kayıt Ol</button>
                                    </div>
                                </div>
                            </form>

                        </div>
                        <!-- end card-body -->
                    </div>
                    <!-- end card -->

                    <div class="row mt-5">
                        <div class="col-sm-12 text-center">
                            <p class="text-muted">Bir Hesabınız Var Mı?<a href="/Login/Index" class="text-primary ml-1"><b>Giriş Yap</b></a></p>
                        </div>

                    </div>
                    <div class="text-danger" asp-validation-summary="ModelOnly">
                        <!--şifre ile genel istemleri aşağıda gösterecek.
                            Şifre en az 6 karakter,en az bir küçük ve bir büyük harf aynı zamanda sayı ve sembol içermeli hatası verecek-->
                    </div>

                </div>
                <!-- end col -->
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </div>
    <!-- end page -->
    <!-- Vendor js -->
    <script src="~/assets/js/vendor.min.js"></script>

    <!-- App js -->
    <script src="~/assets/js/app.min.js"></script>

</body>


</html>