LTS/LTS/ViewComponents/UserMenuViewComponent.cs
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace LTS.ViewComponents
{
    public class UserMenuViewComponent:ViewComponent
    {
        private readonly UserManager<AppUser> _user;

        public UserMenuViewComponent(UserManager<AppUser> user)
        {
            _user = user;
        }

        public async Task<IViewComponentResult> InvokeAsync()//Giriş yapan kişinin bilgileri görünsün
        {
            AppUser users = await _user.GetUserAsync(HttpContext.User);
            return View("Default.cshtml", users);
        }
    }
}

LTS/LTS/Views/Shared/Default.cshtml
@using EntityLayer.Concrete;
@model AppUser
<li class="dropdown notification-list">
    <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
        <img src="~/assets/images/users/avatar-1.jpg" alt="user-image" class="rounded-circle">
        <input type="hidden" asp-for="@Model.Id" />
        <span class="d-none d-sm-inline-block ml-1">@Model.UserName</span>
    </a>
    <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
        <!-- item-->
        <div class="dropdown-header noti-title">
            <h6 class="text-overflow m-0">Hoşgeldiniz !</h6>
        </div>

        <!-- item-->
        <a asp-controller="User" asp-action="UserProfileEdit" class="dropdown-item notify-item">
            <i class="mdi mdi-account-outline"></i>
            <span>Kullanıcı Profili</span>
        </a>


        <div class="dropdown-divider"></div>

        <!-- item-->
        <a asp-controller="Login" asp-action="LogOut" class="dropdown-item notify-item">
            <i class="mdi mdi-logout-variant"></i>
            <span>Çıkış</span>
        </a>

    </div>
</li>

LTS/LTS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LTS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LTS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LTS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LTS/LTS/Views/Shared/_UserLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8" />
    <title>Sidebar Collapsed | Zircos - Responsive Bootstrap 4 Admin Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Responsive bootstrap 4 admin template" name="description" />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="~/assets/images/favicon.ico">

    <!-- App css -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" id="bootstrap-stylesheet" />
    <link href="~/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/app.min.css" rel="stylesheet" type="text/css" id="app-stylesheet" />


</head>
<body>
    <!-- Topbar Start -->
    <div class="navbar-custom">
        <ul class="list-unstyled topnav-menu float-right mb-0">

            <li class="dropdown notification-list">
                <a class="nav-link dropdown-toggle  waves-effect" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                    <i class="mdi mdi-bell noti-icon"></i>
                    <span class="badge badge-success rounded-circle noti-icon-badge">4</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-lg">

                    <!-- item-->

                    <div class="slimscroll noti-scroll">

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-info">
                                <i class="mdi mdi-bell-outline"></i>
                            </div>
                            <p class="notify-details">
                                Updates
                                <small class="text-muted">There are 2 new updates available</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-danger">
                                <i class="mdi mdi-account-plus"></i>
                            </div>
                            <p class="notify-details">
                                New user
                                <small class="text-muted">You have 10 unread messages</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-info">
                                <i class="mdi mdi-comment-account-outline"></i>
                            </div>
                            <p class="notify-details">
                                Caleb Flakelar commented on Admin
                                <small class="text-muted">4 days ago</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-secondary">
                                <i class="mdi mdi-heart"></i>
                            </div>
                            <p class="notify-details">
                                Carlos Crouch liked
                                <b>Admin</b>
                                <small class="text-muted">13 days ago</small>
                            </p>
                        </a>
                    </div>

                    <!-- All-->
                    <a href="javascript:void(0);" class="dropdown-item text-center text-primary notify-item notify-all">
                        Tüm Bildirimleri Gör
                        <i class="fi-arrow-right"></i>
                    </a>

                </div>
            </li>
            @await Component.InvokeAsync("UserMenu")



        </ul>

        <!-- LOGO -->
        <div class="logo-box">
            <a asp-controller="AccountCard" asp-action="Index" class="logo text-center">
                <span class="logo-lg">
                    <img src="~/assets/images/logo-light.png" alt="" height="18">
                    <!-- <span class="logo-lg-text-light">Zircos</span> -->
                </span>
                <span class="logo-sm">
                    <!-- <span class="logo-sm-text-dark">Z</span> -->
                    <img src="~/assets/images/logo-sm.png" alt="" height="24">
                </span>
            </a>
        </div>

    </div>
    <!-- end Topbar -->
    @await Html.PartialAsync("~/Views/User/UserNavbarPartial.cshtml")
    <div>
        @RenderBody()
    </div>
    <!-- Footer Start -->
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @DateTime.Now.Year &copy;Hesap Kart Yönetim Sistemi Tüm Hakları Saklıdır. <a href="#">Sevde Yorulmaz</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- end Footer -->
    <!-- Vendor js -->
    <script src="~/assets/js/vendor.min.js"></script>

    <script src="~/assets/libs/morris-js/morris.min.js"></script>
    <script src="~/assets/libs/raphael/raphael.min.js"></script>

    <script src="~/assets/js/pages/dashboard.init.js"></script>

    <!-- App js -->
    <script src="~/assets/js/app.min.js"></script>
@*    @await RenderSectionAsync("scripts")
*@
</body>
</html>